// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9bMh2a6Pj8iiqSh9AgGAfiFyriGIilFk',
    appId: '1:1013793294324:web:35ca7c7d718cf976525ba1',
    messagingSenderId: '1013793294324',
    projectId: 'vue-curso-da013',
    authDomain: 'vue-curso-da013.firebaseapp.com',
    databaseURL: 'https://vue-curso-da013-default-rtdb.firebaseio.com',
    storageBucket: 'vue-curso-da013.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdRFR-uW_6qC386EhUhmwGj5sbDY_4Yo0',
    appId: '1:1013793294324:android:34cdcf16ec301c16525ba1',
    messagingSenderId: '1013793294324',
    projectId: 'vue-curso-da013',
    databaseURL: 'https://vue-curso-da013-default-rtdb.firebaseio.com',
    storageBucket: 'vue-curso-da013.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf2Fy3Vc4ioskwR76jekUp-Bgm-HljU5E',
    appId: '1:1013793294324:ios:5df3bdae5a1ed2c7525ba1',
    messagingSenderId: '1013793294324',
    projectId: 'vue-curso-da013',
    databaseURL: 'https://vue-curso-da013-default-rtdb.firebaseio.com',
    storageBucket: 'vue-curso-da013.firebasestorage.app',
    iosBundleId: 'com.example.sosaguas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf2Fy3Vc4ioskwR76jekUp-Bgm-HljU5E',
    appId: '1:1013793294324:ios:5df3bdae5a1ed2c7525ba1',
    messagingSenderId: '1013793294324',
    projectId: 'vue-curso-da013',
    databaseURL: 'https://vue-curso-da013-default-rtdb.firebaseio.com',
    storageBucket: 'vue-curso-da013.firebasestorage.app',
    iosBundleId: 'com.example.sosaguas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_mURub9o4jR0OILUW6gkSgLV58Kxda5c',
    appId: '1:1013793294324:web:5d7a340fa1e55fb5525ba1',
    messagingSenderId: '1013793294324',
    projectId: 'vue-curso-da013',
    authDomain: 'vue-curso-da013.firebaseapp.com',
    databaseURL: 'https://vue-curso-da013-default-rtdb.firebaseio.com',
    storageBucket: 'vue-curso-da013.firebasestorage.app',
  );
}
