name: sos_aguas
description: "SOS Aguas"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4 #tela de loading

  shared_preferences: ^2.5.2

  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5

  google_maps_flutter: ^2.10.1

  geolocator: ^13.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash.png

flutter_native_splash:
  color: "#e1f5fe"
  image: assets/splash.png
  color_dark: "#042a49"
  image_dark: assets/splash.png
  android_12:
    image: assets/splash.png
    color: "#42a5f5"
    icon_background_color: "#eeeeee"